#!/usr/bin/env python3
"""Generate test_tracks/summary.md from expectations + cached features.

Reads expectations.yaml, runs interpret_features() against each track's
cached features, aggregates per-track pass rates by check category, and
writes a markdown summary.  Tracks without a cached feature file are
skipped (and listed under "Skipped").

Run after editing expectations.yaml; a Claude Code hook in
.claude/settings.json invokes this automatically.

Usage:
    PYTHONPATH=. .venv/bin/python3.12 scripts/generate_test_summary.py
"""
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
EXPECTATIONS = ROOT / "test_tracks" / "expectations.yaml"
CACHE_DIR = ROOT / "test_tracks" / "features_cache"
SUMMARY = ROOT / "test_tracks" / "summary.md"

sys.path.insert(0, str(ROOT))

from app.services.analysis import interpret_features, load_features  # noqa: E402
from scripts.run_track_tests import compare  # noqa: E402


def passes(checks: list, label: str) -> bool | None:
    """Return True/False if `label` is in checks; None if not present."""
    for ok, lbl, *_ in checks:
        if lbl == label:
            return bool(ok)
    return None


def all_pass(checks: list, labels: list[str]) -> bool | None:
    """Return True if all labels present and pass; False if any present and fail;
    None if none of the labels are present (track has no expectation in this category)."""
    statuses = [passes(checks, lb) for lb in labels]
    present = [s for s in statuses if s is not None]
    if not present:
        return None
    return all(present)


def fmt_row(name: str, passed: int, total: int) -> str:
    pct = (100 * passed / total) if total else 0.0
    return f"| {name} | {passed} | {total} | {pct:.1f}% |"


def main() -> int:
    tracks = yaml.safe_load(EXPECTATIONS.read_text())["tracks"]

    categories = {
        "Key — start (root + mode)": ["key.root", "key.mode"],
        "Key — end (root + mode)": ["key_end.root", "key_end.mode"],
        "Key — all four": ["key.root", "key.mode", "key_end.root", "key_end.mode"],
        "BPM (start + end)": ["bpm", "bpm_end"],
        "Tuning (start + end)": ["tuning", "tuning_end"],
        "no_drums": ["no_drums"],
        "swing": ["swing"],
        "bars_percussion": ["bars_percussion"],
        "no_key": ["no_key"],
        "no_tempo": ["no_tempo"],
    }
    counts = {name: [0, 0] for name in categories}  # name -> [passed, total]
    failing_tracks: list[tuple[str, list[str]]] = []
    skipped: list[str] = []
    evaluated = 0

    for track in tracks:
        title = track["title"]
        wav = ROOT / track["file"]
        cache = CACHE_DIR / (wav.stem + ".json")
        if not cache.exists():
            skipped.append(title)
            continue

        features = load_features(str(cache))
        result = interpret_features(features)
        checks = compare(result, track["expected"])
        evaluated += 1

        track_failures: list[str] = []
        for cat_name, labels in categories.items():
            status = all_pass(checks, labels)
            if status is None:
                continue
            counts[cat_name][1] += 1
            if status:
                counts[cat_name][0] += 1
            else:
                track_failures.append(cat_name)
        if track_failures:
            failing_tracks.append((title, track_failures))

    lines: list[str] = []
    lines.append("# Test corpus accuracy")
    lines.append("")
    lines.append(
        f"Last updated: {date.today().isoformat()} — {evaluated} track"
        f"{'s' if evaluated != 1 else ''} evaluated"
        + (f", {len(skipped)} skipped (no cached features)" if skipped else "")
        + "."
    )
    lines.append("")
    lines.append(
        "Each row counts a track as passing only if **all** sub-checks in that "
        "category match the expectation.  Tracks without an expectation in a "
        "category are excluded from that row's denominator."
    )
    lines.append("")
    lines.append("| Check | Pass | Total | % |")
    lines.append("|---|---|---|---|")
    for cat_name in categories:
        passed, total = counts[cat_name]
        if total == 0:
            continue
        lines.append(fmt_row(cat_name, passed, total))
    lines.append("")

    if failing_tracks:
        lines.append("## Failing tracks")
        lines.append("")
        for title, cats in failing_tracks:
            lines.append(f"- **{title}** — {', '.join(cats)}")
        lines.append("")

    if skipped:
        lines.append("## Skipped (no cached features)")
        lines.append("")
        for title in skipped:
            lines.append(f"- {title}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by `scripts/generate_test_summary.py` from cached features. "
        "Re-cache by running `scripts/run_track_tests.py --reextract`.*"
    )

    SUMMARY.write_text("\n".join(lines) + "\n")
    print(f"Wrote {SUMMARY.relative_to(ROOT)} ({evaluated} tracks).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
