"""Refresh YouTube cookies using a saved Playwright storage state.

Reads YT_STORAGE_STATE_B64 (base64-encoded storage_state.json) from env,
launches headless Chromium with that state, visits youtube.com to renew
the session, exports the cookies in Netscape cookies.txt format, and
writes them to --out. Exits non-zero if the session no longer appears
signed in (which is the signal to re-run scripts/yt_login_local.py).
"""
from __future__ import annotations

import argparse
import base64
import os
import sys
import tempfile
from pathlib import Path

from playwright.sync_api import sync_playwright

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by scripts/refresh_yt_cookies.py — do not edit.\n"
)

SIGNED_IN_MARKERS = ("SID", "SAPISID", "__Secure-3PSID", "__Secure-1PSID")


def to_netscape(cookies: list[dict]) -> str:
    lines = [NETSCAPE_HEADER]
    for c in cookies:
        domain = c.get("domain") or ""
        if not domain:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        raw_exp = c.get("expires", 0)
        expires = int(raw_exp) if isinstance(raw_exp, (int, float)) and raw_exp > 0 else 0
        name = c.get("name") or ""
        value = c.get("value") or ""
        lines.append("\t".join([domain, include_sub, path, secure, str(expires), name, value]))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="cookies.txt")
    args = parser.parse_args()

    blob = os.environ.get("YT_STORAGE_STATE_B64", "")
    if not blob:
        print("ERROR: YT_STORAGE_STATE_B64 env var is empty", file=sys.stderr)
        return 2

    state_bytes = base64.b64decode(blob)
    with tempfile.NamedTemporaryFile("wb", suffix=".json", delete=False) as tf:
        tf.write(state_bytes)
        state_path = tf.name

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(storage_state=state_path)
            page = context.new_page()
            page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=60_000)
            page.wait_for_timeout(5_000)

            cookies = context.cookies([
                "https://www.youtube.com",
                "https://youtube.com",
                "https://music.youtube.com",
            ])
            names = {c.get("name") for c in cookies}
            if not any(m in names for m in SIGNED_IN_MARKERS):
                print(
                    f"ERROR: storage state no longer signed in. Cookie names seen: {sorted(n for n in names if n)}",
                    file=sys.stderr,
                )
                browser.close()
                return 3

            out_path = Path(args.out)
            out_path.write_text(to_netscape(cookies))
            print(f"Wrote {len(cookies)} cookies to {out_path} ({out_path.stat().st_size} bytes)")
            browser.close()
    finally:
        try:
            os.unlink(state_path)
        except OSError:
            pass

    return 0


if __name__ == "__main__":
    sys.exit(main())
